remote_theme: sighingnow/jekyll-gitbook
title: portfolio
# description: none
author: issam-eddine
# email: first-name.family-name@example.com
social:
  linkedin: https://www.linkedin.com/in/issam-eddine/
navigation: _data/navigation.yml